### ISSUE TITLE
Add support for Scala 2.13

### ISSUE THREAD

**Issue by melgenek** [snowplow/snowplow-scala-tracker#126]
Hello! 

I am trying to move our project to scala 2.13 and figured out that there is a dependency on snowplow-scala-tracker. So it would be nice to compile this project with scala 2.13.

I have an implementation of this change. However this project depends on [iglu core](https://github.com/melgenek/iglu/tree/master/0-common/scala-core). 
I used the locally published version of iglu/core with scala 2.13 to update the tracker. 

So, I could create a pr into this repo with the updated scala, but I need the https://github.com/snowplow/iglu/pull/494 to be released first.

There is also an issue that my iglu/core pr is based on master with 0.4.0 version of iglu/core, but the latest master of snowplow-scala-tracker relies on 0.5.1, which I was not able to find in the iglu/core repo. Could somebody please point me to that changes because they seem to be in any other branch or repo?

**Comment by lukeindykiewicz** [comment]
Hi @melgenek 
The snowplow/iglu is deprecated, as we move things out of mono repos to specific repos. We've already created the issue for updating the readme (https://github.com/snowplow/iglu/issues/495), thanks.
The repo you're looking for is: https://github.com/snowplow-incubator/iglu-scala-core. There is `0.5.1` code.

**Comment by melgenek** [comment]
@lukeindykiewicz thank you! @chuwy has already told me about this. I will prepare a new pr as soon as possible.
