### ISSUE TITLE
Test changes to the Scala Tracker by sending events through the Kinesis pipeline

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-scala-tracker#14]
This will be a good way to get familiar with what happens to the Tracker's output. You don't actually need to use Amazon Kinesis - you can run the Scala Stream Collector locally and configure it to print its output to stdout rather than sending it to Kinesis, and pipe its output into Scala Kinesis Enrich.

The idea is that if the events generated by the Tracker are well-formed, SKE will enrich them and print the enriched events in TSV format to stdout. If the events are not well-formed (e.g. fields are of the wrong type) then SKE will print a JSON to stderr containing the original data received from the Tracker and an array of error messages describing what was wrong with it.

Let me know if you have any questions about this.

Resources:

https://github.com/snowplow/snowplow/wiki/Configure-the-Scala-Stream-Collector
https://github.com/snowplow/snowplow/wiki/Configure-Scala-Kinesis-Enrich

**Comment by alexanderdean** [comment]
Great suggestion Fred!

**Comment by alexanderdean** [comment]
(Note that this ticket doesn't need to go in the changelog)

**Comment by alexanderdean** [comment]
This is done, closing
