### ISSUE TITLE
Add dvce_sent_tstamp

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-scala-tracker#15]
See https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol#12-date--time-parameter

This is a timestamp added to the event just before it is sent. This could be some time after the event was actually created, as in these circumstances:
- A tracker being unable to send an event immediately because the device is offline
- A tracker saving events to batch together in POSTs

So far, no tracker has implemented this feature. (Edit: this is wrong, the mobile trackers have!)

An example of how it will be used: https://github.com/snowplow/snowplow/issues/1550

**Comment by alexanderdean** [comment]
The mobile trackers have had this feature for some time - @jbeemster can explain more:

https://github.com/snowplow/snowplow-android-tracker/blob/master/CHANGELOG#L47

https://github.com/snowplow/snowplow-objc-tracker/issues/158

**Comment by fblundun** [comment]
I did not know that! Glad that the dvce_sent_tstamp field is no longer just theoretical...

**Comment by jbeemster** [comment]
This has indeed been implemented on both of the Trackers.  Essentially you need to add the "stm" field just before sending.  For "GET"s you add a new one for each Request; for "POST"s you add the same "stm" to all the events that will go into that Request.
