### ISSUE TITLE
CE3 compatible release

### ISSUE THREAD

**Issue by andreamarcolin** [snowplow/snowplow-scala-tracker#156]
It would be great to have a CE3 compatible release, now that CE3 has been out for a while and most of the OSS community already transitioned to the new major release.

I have seen a couple of strategies in the wild to do that: some library authors have chosen to just upgrade and release a new major version (changes required by the switch almost certainly break both source and binary compatiblity). Others, particularly the most used libraries like http4s and fs2, have chosen to maintain two versions (e.g. 0.22.x and 0.23.x) built against CE2 and CE3 respectively. Typically, both would also cross-build for Scala 2.12, 2.13 and 3, giving end users the freedom to decide undertake whatever migration they want first (CE2 -> CE3 or Scala 2 -> Scala 3), but this is another topic, and cross-building our tracker for Scala 3 might not be possible yet.

The first option probably forces the hand a bit more, but it comes with a significantly lower effort in the medium term I believe (not having to maintain two parallel branches.

For this specific case, I'm slightly leaning towards the first option if we don't expect high development activity feature-wise, so that if users chose to not update (because they are still stuck on CE2 for example) they don't miss out on important features. 
One thing to consider is that in my experience end-users on the FP ecosystem tend to be on top of new releases, so they might be already or probably close to a CE3 upgrade. OOP/Imperative Scala users, on the other hand, might not even have CE3 on the classpath if it wasn't for our tracker, so they might be free to upgrade... and even if they had something else bringing in CE2, most of the Scala libraries built on CE have already published at least a version for CE3.

I can't back any of that with data, so I'm happy to be proven wrong and I would like to have the discussion :)

Looking for some feedback here, particularly from @istreeter and @chuwy I guess?

**Comment by istreeter** [comment]
We should consider removing cats effect as a dependency of the `core` module.  We only use it in `core` because we use the `Clock` -- and we could easily replace that with a custom `TimeProvider` trait.  This would completely solve the problem you describe for users of the id-emitter.  Cats Effect does not need to be on their class path at all.

So this discussion becomes relevant only for the `http4s` module, which is relatively new anyway.  I am OK with just maintaining a CE3 version only of that emitter.

We could consider doing one final release with CE2, just to make sure there is a viable alternative with all the latest dependencies.  And switch to CE3 after that.

**Comment by andreamarcolin** [comment]
Yeah that makes sense. I could probably try to spend some time on this when I will be back in a couple of weeks.

Meanwhile, I had a look in the core module... any suggestion on how to deal with things like:
```scala 
Sync[F].delay(client(Http(url)).body)
```
or 
```scala
Concurrent.timeoutTo(getInstanceContext.map(_.some), 3.seconds, Option.empty[SelfDescribingJson].pure[F])
```
?

**Comment by chuwy** [comment]
That's a very good (yet unpleasant) point @andreamarcolin. Even if we get rid of CE dependency in `core`, we still have `metadata` module, in which case I guess it's also fine to say "we support metadata only if you use CE (or maybe even http4s)", which is bad, but to me looks acceptable.

And I have no objections about full-CE3-release-after-last-CE2 strategy.

**Comment by chuwy** [comment]
As of making `core` CE-free, I'd propose combining two existing capability traits into one:

```scala
trait Emitter[F[_]] {
  def getTstamp: F[Long]
  def getUuid: F[UUID]
}

// In http4s module (alas, requires an additional import)
import cats.effect.std.UUIDGen
import cats.effect.kernel.Clock

implicit def catsEffectEmitter[F[_]](implicit C: Clock[F], U: UUIDGen[F]): Emitter[F] = ???
```
