### ISSUE TITLE
Add a custom context based on EC2 instance metadata

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-scala-tracker#2]
Resources:
- https://github.com/takus/fluent-plugin-ec2-metadata
- https://github.com/dump247/aws-mock-metadata
- https://github.com/femto113/node-ec2-instance-data/blob/master/index.js
- https://github.com/tramzee/ec2-metadata/blob/master/src/io/hivewing/ec2_metadata.clj

**Comment by alexanderdean** [comment]
This will be super useful for making sense of the Kinesis app-sent events...

**Comment by alexanderdean** [comment]
Hey @chuwy - can we tighten up the name of this ticket? It's a bit general, when it should be specific (the specific context we are adding to our events).

**Comment by alexanderdean** [comment]
Also - can we check that it behaves safely when run on a box that isn't EC2?

**Comment by chuwy** [comment]
As about box that isn't EC2: function `EC2.getContext` returns `Option[SelfDescribingJson]` which is `None` if we can't get it for any reasons (parse error, Future timeout, etc) and Some if everything is ok. So user can call `toSeq` on it and safely add to other contexts. 
As about name: "Add a custom context based on EC2 instance identity document"?

**Comment by alexanderdean** [comment]
> As about box that isn't EC2: function EC2.getContext returns Option[SelfDescribingJson] which is None if we can't get it for any reasons (parse error, Future timeout, etc) and Some if everything is ok. So user can call toSeq on it and safely add to other contexts. 

Sounds good!

> As about name: "Add a custom context based on EC2 instance identity document"?

Sounds good too.
