### ISSUE TITLE
Eliminate akka system startup delay

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-scala-tracker#22]
First request on all emitters sending with ~3 seconds delay. Reason is that akka system initialized in object constructor, which is lazy and waiting for first method call.
It also affects EC2 context, because we need to send first events without attached context or make blocking request to "warm up" system.
One proposed solution to allow user inject and reuse his own akka system.

**Comment by fblundun** [comment]
We could make the emitter class optionally configurable with a user-provided actor system, falling back on a built-in default if the user isn't using Akka.

When using an asynchronous emitter, is the delay affecting the user's thread? Or is it just happening on the tracker's internal worker thread?

**Comment by chuwy** [comment]
@fblundun everything inside internal thread.

**Comment by fblundun** [comment]
I think that this is not too bad as long as the user's thread doesn't experience the delay. But it's still surprising that the delay is so long - investigating how to reduce it should be interesting.

**Comment by fblundun** [comment]
There's a design decision to be made over the EC2 context - whether to send events without it, or to delay events until it becomes available.

To delay events until the context is available, you could put the result of the EC2 context lookup in a `Future` and send the events in a callback on that future.

**Comment by chuwy** [comment]
Is it too bad to provide only two approaches in this release (blocking initialization and temporarily empty context)? Because I can't see any way to provide sane API with callbacks on `Future[Context]` now.

**Comment by fblundun** [comment]
I think that it's fine to leave waiting for the context to become available until the next release.

**Comment by chuwy** [comment]
Pushing back to 0.4.0. This will involve little refactoring of how Emitters are work.

**Comment by chuwy** [comment]
Resolved by #49
