### ISSUE TITLE
Add support for dvce_sent_tstamp

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-scala-tracker#27]
This is related to: https://github.com/snowplow/snowplow/issues/2457

**Comment by alexanderdean** [comment]
Bringing forwards

**Comment by chuwy** [comment]
Duplicate? https://github.com/snowplow/snowplow-scala-tracker/issues/15

**Comment by alexanderdean** [comment]
Sorry yes, closing

**Comment by chuwy** [comment]
Sorry for didn't noticed it earlier.
