### ISSUE TITLE
Fix incorrect `instance_identity_document` jsonschema

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-scala-tracker#29]
Ec2Metadata context is sending an invalid JsonSchema:

https://github.com/snowplow/snowplow-scala-tracker/blob/2aa8ce3f6e4f77b3274a605c67a7f5a95582b893/src...

`iglu:com.amazon.aws.ec2/instance_identity_document` => `iglu:com.amazon.aws.ec2/instance_identity_document/jsonschema/1-0-0`

**Comment by chuwy** [comment]
Trying to figure out how that could happen.
