### ISSUE TITLE
 Add support for attaching true timestamp to events

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-scala-tracker#38]
Bringing forwards

**Comment by chuwy** [comment]
Duplicate? https://github.com/snowplow/snowplow-scala-tracker/issues/28

**Comment by alexanderdean** [comment]
Sorry yes, closing. Really nice implementation by the way...

**Comment by chuwy** [comment]
Cool. I worried about implementation, since I'm not a huge fan of this usage for implicits.
