### ISSUE TITLE
Repository not indexed

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow-scala-tracker#39]
Your maven repository (assuming you only have one is also suffering from this issue):

http://stackoverflow.com/questions/34104305/resource-nexus-maven-repository-index-properties-does-not-exist-in-intellij

Please fix it.

**Comment by alexanderdean** [comment]
Assigning to @ninjabear to clarify...

**Comment by ninjabear** [comment]
This issue will be closed by the move to mavencentral/jcenter! When using a private repository there's an option to provide an index that's essentially a list of everything the repository provides. Tools like intellij use this to help you create buildscripts amongst other things (it could let you know there's a newer version available for another example).

**Comment by chuwy** [comment]
We've moved to Maven Central. Closing.
