### ISSUE TITLE
Fix Gradle and Maven sections of setup guide

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-scala-tracker#40]
Currently: https://github.com/snowplow/snowplow/wiki/Scala-Tracker-Setup#23-gradle

See @ninjabear's comment https://github.com/snowplow/snowplow-android-tracker/issues/167#issuecomment-217491483 for the corrected coordinates.

**Comment by alexanderdean** [comment]
This is a documentation ticket - no need to add to CHANGELOG, please close and de-assign from milestone when done.

**Comment by chuwy** [comment]
Closing.
