### ISSUE TITLE
Add support for Google Compute Engine metadata

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-scala-tracker#45]
https://cloud.google.com/compute/docs/metadata#default

**Comment by chuwy** [comment]
Hey @alexanderdean! Having that GCE is very close, do you think it's worth to bring it to 0.5.0?

**Comment by alexanderdean** [comment]
Very close to what @chuwy ?

**Comment by chuwy** [comment]
To us working on it (I meant Google Cloud, not GCE particularly)

**Comment by alexanderdean** [comment]
Yes, good point...

**Comment by alexanderdean** [comment]
Not sure how this works in a Docker containerized / Cloud Dataflow world though...
