### ISSUE TITLE
Add trackError method

### ISSUE THREAD

**Issue by kazjote** [snowplow/snowplow-scala-tracker#47]
We would like to contribute implementation of error tracking in Scala Tracker.

1. Have you already thought about implementing it? Do you have any suggestions? For us it would be enough to have ```trackError``` method. 

In _Javascript Tracker_ it has following arguments:
```javascript
function track(message, filename, lineno, colno, error, contexts)
```

2. However, I don't fully understand the use case of _filename_, _lineno_ and _colno_ arguments. Do you think we need them also in _Scala Tracker_? Maybe we could fill them in based on stack trace of the exception?

3. I was thinking also about filling in fields _className_, _isFatal_, _threadId_ and _threadName_ but am not sure what is the use case of these either.

Thanks!

**Comment by jbeemster** [comment]
Hey @kazjote you can see the Android implementation of the Exception tracking which might help understand a few of the other fields:

> https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/tracker/ExceptionHandler.java
