### ISSUE TITLE
Make API referentially-transparent

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow-scala-tracker#74]
...by introducing cats-effect.

I'm slightly hazy on this one as tracker often used in non-RT applications and libraries and its easier to wrap everything in `IO` on caller side when necessary rather than call `unsafeRunSync()` for people who are not familiar with cats. As a counter-argument, `IO`-types can simplify retry-behavior.

Leaving decision to @BenFradet and @asoltysik.

**Comment by asoltysik** [comment]
@BenFradet what's your opinion? I'm quite neutral on this one.

**Comment by BenFradet** [comment]
We should promote what we want people to be doing so I'd be for exposing `F`

**Comment by chuwy** [comment]
Ideally tacker should be a simple interface with zero dependencies (maybe without JSON lib as turning JSON into bytes looks like low-level operation to me): 

```scala
trait Tracker[F[_]] {
  def emitters: List[Emitter[F]]
  def track(event: Event): F[Unit] =        // Without any constraints such as Sync
    emitters.traverse(_.submit(event))
}
```

And emitters released separately with `Sync` constraint or simply `Id` as per https://github.com/snowplow/snowplow-scala-tracker/issues/46

**Comment by BenFradet** [comment]
makes sense, I added #46 to 0.6.0
